name: Daily Auto Login

on:
  schedule:
    - cron: '0 19 * * *'  # 每天北京时间 03:00
  workflow_dispatch:

jobs:
  auto-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Login Script
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
        run: python login.py
